
spring:
    profiles:
        active: prod
    devtools:
        restart:
            enabled: false
        livereload:
            enabled: false
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:mysql://172.19.28.133:3306/org_db?useUnicode=true&characterEncoding=utf8&useSSL=false
        name:
        username: cuidaren
        password: CuiDaRen!23456
        hikari:
            data-source-properties:
                cachePrepStmts: true
                prepStmtCacheSize: 250
                prepStmtCacheSqlLimit: 2048
                useServerPrepStmts: true
    jpa:
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        database: MYSQL
        show-sql: false
        properties:
            hibernate.cache.use_second_level_cache: true
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: false
            hibernate.javax.cache.provider: org.ehcache.jsr107.EhcacheCachingProvider
            hibernate.javax.cache.uri: ${spring.cache.jcache.config}
            hibernate.cache.region.factory_class: cn.fintecher.cuibei.config.jcache.SpringCacheRegionFactory
    cache:
        jcache:
            config: ehcache.xml
    redis:
      database: 0
      host: 172.19.28.135
      port: 6379
eureka:
  instance:
    hostname: organization-service
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
            defaultZone: http://172.19.28.135:8761/eureka/
server:
    port: 9005

