server:
    port: 8081

spring:
    application:
        name: summons-eureka

eureka:
    instance:
        hostname: localhost
        lease-expiration-duration-in-seconds: 30
        lease-renewal-interval-in-seconds: 30
    client:
        registerWithEureka: false
        fetchRegistry: false
        serviceUrl:
            defaultZone: http://localhost:8081/eureka/
    server:
        enable-self-preservation: false

endpoints:
   shutdown:
        enabled: true